server:
  port: 8081
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: hong
    password: hong1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
                                                            #네이밍 전량
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #->변수 이름을 그대로 사용,SpringPhysicalNamingStrategy(Default)->Camel case를 underscore 형태로 변경해서 매핑
      use-new-id-generator-mappings: false  #jpa의 기본 넘버링 전략을 따라가지 않는다# => @GeneratedValue(strategy = GenerationType.IDENTITY)과 연관
    show-sql: true #콘솔창에 SQL 노출
    properties:
      hibernate:
        format_sql: true #SQL 한 줄로X 정렬해서

  jackson:
    serialization:
      fail-on-empty-beans: false
